#ifndef MENUBARACTIONIDS_H
#define MENUBARACTIONIDS_H

namespace MenuBar {

enum ActionID {
    // File Menu
    NEW,
    OPEN,
    SAVE,
    SAVE_AS,
    GENERATE_MAP,
    CLOSE,
    IMPORT_MAP,
    IMPORT_MONSTERS,
    IMPORT_MINIMAP,
    EXPORT_MINIMAP,
    EXPORT_TILESETS,
    RELOAD_DATA,
    RECENT_FILES,
    PREFERENCES,
    EXIT,
    
    // Edit Menu
    UNDO,
    REDO,
    FIND_ITEM,
    FIND_CREATURE,
    REPLACE_ITEMS,
    REFRESH_ITEMS,
    AUTOMAGIC,
    BORDERIZE_SELECTION,
    BORDERIZE_MAP,
    RANDOMIZE_SELECTION,
    RANDOMIZE_MAP,
    MAP_REMOVE_UNREACHABLE_TILES,
    CLEAR_INVALID_HOUSES,
    CLEAR_MODIFIED_STATE,
    CUT,
    COPY,
    PASTE,
    
    // Search Menu (integrated into other menus)
    SEARCH_ON_MAP_EVERYTHING,
    SEARCH_ON_MAP_ZONES,
    SEARCH_ON_MAP_UNIQUE,
    SEARCH_ON_MAP_ACTION,
    SEARCH_ON_MAP_CONTAINER,
    SEARCH_ON_MAP_WRITEABLE,
    SEARCH_ON_SELECTION_EVERYTHING,
    SEARCH_ON_SELECTION_ZONES,
    SEARCH_ON_SELECTION_UNIQUE,
    SEARCH_ON_SELECTION_ACTION,
    SEARCH_ON_SELECTION_CONTAINER,
    SEARCH_ON_SELECTION_WRITEABLE,
    SEARCH_ON_SELECTION_ITEM,
    REPLACE_ON_SELECTION_ITEMS,
    REMOVE_ON_SELECTION_ITEM,
    
    // Selection Mode (integrated into Selection menu)
    SELECT_MODE_COMPENSATE,
    SELECT_MODE_CURRENT,
    SELECT_MODE_LOWER,
    SELECT_MODE_VISIBLE,
    
    // View Menu
    NEW_VIEW,
    NEW_DETACHED_VIEW,
    TOGGLE_FULLSCREEN,
    TAKE_SCREENSHOT,
    ZOOM_IN,
    ZOOM_OUT,
    ZOOM_NORMAL,
    SHOW_ALL_FLOORS,
    SHOW_AS_MINIMAP,
    SHOW_PREVIEW,
    SHOW_LIGHTS,
    
    // Map Menu
    EDIT_TOWNS,
    MAP_CLEANUP,
    MAP_PROPERTIES,
    MAP_STATISTICS,
    
    // Navigate Menu
    GOTO_PREVIOUS_POSITION,
    GOTO_POSITION,
    FLOOR_0,
    FLOOR_1,
    FLOOR_2,
    FLOOR_3,
    FLOOR_4,
    FLOOR_5,
    FLOOR_6,
    FLOOR_7,
    FLOOR_8,
    FLOOR_9,
    FLOOR_10,
    FLOOR_11,
    FLOOR_12,
    FLOOR_13,
    FLOOR_14,
    FLOOR_15,
    
    // Window Menu
    WIN_MINIMAP,
    NEW_PALETTE,
    DESTROY_PALETTE,
    SELECT_TERRAIN,
    SELECT_DOODAD,
    SELECT_ITEM,
    SELECT_COLLECTION,
    SELECT_HOUSE,
    SELECT_CREATURE,
    SELECT_WAYPOINT,
    SELECT_RAW,
    VIEW_TOOLBARS_BRUSHES,
    VIEW_TOOLBARS_POSITION,
    VIEW_TOOLBARS_SIZES,
    VIEW_TOOLBARS_STANDARD,
    VIEW_PALETTE_DOCK,
    VIEW_MINIMAP_DOCK,
    VIEW_PROPERTIES_DOCK,

    // Perspective Management
    SAVE_PERSPECTIVE,
    LOAD_PERSPECTIVE,
    RESET_PERSPECTIVE,

    // Dockable Views
    NEW_DOCKABLE_VIEW,
    CLOSE_DOCKABLE_VIEWS,
    
    // Experimental Menu
    EXPERIMENTAL_FOG,
    
    // About Menu
    EXTENSIONS,
    GOTO_WEBSITE,
    ABOUT,
    SHOW_HOTKEYS,
    
    // Server Menu (custom addition)
    HOST_SERVER,
    CONNECT_TO_SERVER,
    
    // Toolbar-specific actions
    TOOLBAR_POSITION_GO,
    TOOLBAR_SIZES_CIRCULAR,
    TOOLBAR_SIZES_RECTANGULAR,
    TOOLBAR_SIZES_1,
    TOOLBAR_SIZES_2,
    TOOLBAR_SIZES_3,
    TOOLBAR_SIZES_4,
    TOOLBAR_SIZES_5,
    TOOLBAR_SIZES_6,
    TOOLBAR_SIZES_7,

    // Brush toolbar actions
    PALETTE_TERRAIN_OPTIONAL_BORDER_TOOL,
    PALETTE_TERRAIN_ERASER,
    PALETTE_TERRAIN_PZ_TOOL,
    PALETTE_TERRAIN_NOPVP_TOOL,
    PALETTE_TERRAIN_NOLOGOUT_TOOL,
    PALETTE_TERRAIN_PVPZONE_TOOL,
    PALETTE_TERRAIN_ZONE_BRUSH,
    PALETTE_TERRAIN_NORMAL_DOOR,
    PALETTE_TERRAIN_LOCKED_DOOR,
    PALETTE_TERRAIN_MAGIC_DOOR,
    PALETTE_TERRAIN_QUEST_DOOR,
    PALETTE_TERRAIN_NORMAL_ALT_DOOR,
    PALETTE_TERRAIN_ARCHWAY_DOOR,
    PALETTE_TERRAIN_HATCH_DOOR,
    PALETTE_TERRAIN_WINDOW_DOOR,

    // Additional actions for Qt-specific features
    GROUND_VALIDATION,
    IMPORT_MAP_DIALOG,
    EXPORT_MINIMAP_DIALOG,
    GOTO_POSITION_DIALOG
};

} // namespace MenuBar

#endif // MENUBARACTIONIDS_H
